### ISSUE TITLE
Caps on schematic?

### ISSUE THREAD

**Issue by BitKnitting** [CircuitSetup/Split-Single-Phase-Energy-Meter#1]
Looking at the datasheet for DVDD on atm90e32.  Notes DVD should be decoupled w/ 10uF and .1 uF.  Where is the 10uF?

Also, VDD18 notes only need a 10uF cap.  why .1uF tied here? I'm thinking DVDD and VDD18 swapped?

**Comment by CircuitSetup** [comment]
You are correct! That is something I initially left out but will be adding for the final version. It's actually not in the Application note examples, and I'm not sure why.

**Comment by CircuitSetup** [comment]
This is fixed in the latest version. See here: https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/blob/master/Hardware/energy_meter_pcb_v1.4.png
