### ISSUE TITLE
Does Current Transformer Hookup Photo match the instructions?

### ISSUE THREAD

**Issue by lyzby** [CircuitSetup/Split-Single-Phase-Energy-Meter#13]
Regarding the picture of the Current Transformers attached to the mains wires, it appears that they are clamped in such a way that the arrows on both would be pointed down.

The directions say "CT2 should point in the opposite direction as CT1". I took that to mean that CT1's arrow should point down and CT2's should point up. Is the photo incorrect or am I misunderstanding?

**Comment by CircuitSetup** [comment]
Good eye! The photo is incorrect. I should take a new one to illustrate this better, or at least make a little diagram. Sorry it is confusing.

**Comment by CircuitSetup** [comment]
I updated the photo with some arrows to illustrate this.
