### ISSUE TITLE
Code for 6 channel board?

### ISSUE THREAD

**Issue by p-doyle** [CircuitSetup/Split-Single-Phase-Energy-Meter#16]
Is there a release binary for the esp32 that will work with the 6 channel board?  Or source code?  I saw a src_6chan folder in https://github.com/CircuitSetup/EmonESP but it doesn't seem compatible with the ATM90E32 library.

**Comment by CircuitSetup** [comment]
I have something similar for the 6 channel, but it's not up to date with the current version of EmonESP. I'll try to post this in the 6 channel repository soon.

**Comment by CircuitSetup** [comment]
Located here: https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/tree/master/Software/EmonESP
