### ISSUE TITLE
External wifi antenna?

### ISSUE THREAD

**Issue by BitKnitting** [CircuitSetup/Split-Single-Phase-Energy-Meter#17]
The ESP32 freezes up after about 7 hours (or so...) I'm thinking it is because the wifi connection is not strong enough.  Has anyone put an external antenna on their ESP32?  If so, any recommendations, gotchas?

Thank you.

**Comment by CircuitSetup** [comment]
What specific software are you running?  Also what is the rssi value?

There is an esp32 dev module with an external antenna connection.

**Comment by gigawatts** [comment]
Speaking of RSSI, it would be awesome to add that as one of the values available via MQTT, so it can be graphed/monitored over time.

**Comment by CircuitSetup** [comment]
@BitKnitting I meant to post this version of the DevKitC- https://www.mouser.com/ProductDetail/Espressif-Systems/ESP32-DevKitC-32U?qs=sGAEpiMZZMuJ3l9lTgMBp1ZUJQFPkBG2sDWyUw9oyIyrWi1BCP7QAQ%3D%3D
