### ISSUE TITLE
How to calculate CurrentGainCT#

### ISSUE THREAD

**Issue by lanhtudongxanh** [CircuitSetup/Split-Single-Phase-Energy-Meter#18]
Hi there, 
 In the energy_meter.h file, I see below: 
  /*
   25498 - SCT-013-000 100A/50mA
   39473 - SCT-016 120A/40mA
   46539 - Magnalab 100A
*/
#define CURRENT_GAIN_CT1 39473
#define CURRENT_GAIN_CT2 39473
but I use the DLXQ 20 100A/100mA current sensor. So I don't understand how to you calculate CURRENT_GAIN_CT# for it. Please help me, calculate the CURRENT_GAIN_CT for my current sensor.
Thank you!

**Comment by CircuitSetup** [comment]
Hello! I haven't had an opportunity to test this CT myself, so I don't have a calibration value. I can estimate the value to be around 13000, assuming it has a 100mA output. 

Please see the calibration procedure here to get a more accurate calibration value: https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter#calibration

**Comment by BitKnitting** [comment]
Hi, Perhaps a short write up I did
<https://github.com/BitKnitting/FitHome/wiki/EnergyMonitorFirmware#calibration>
will help please let me know if the info can be improved (assuming it was
helpful at all).
