### ISSUE TITLE
Voltage calibration value

### ISSUE THREAD

**Issue by gigawatts** [CircuitSetup/Split-Single-Phase-Energy-Meter#29]
In the [latest release](https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/releases/tag/v2.5.7), you list "29462" as the default value we should set, but that conflicts with the "default" value you list on the emonESP's own configuration page of "37106", which is also in your screenshot [here](https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/blob/master/README.md#calibration)

When I set the default you suggested in your release notes of "29462", my system was reading around 100 volts, instead of the 125v it was actually sitting at.

Setting mine to 37106 corrected the calibration, but I just figured I would let you know about the discrepancy you posted, so other's are not confused when they follow those instructions.

**Comment by CircuitSetup** [comment]
Thanks, I'll make that correction!
