### ISSUE TITLE
When in STA mode connected to AP and AP goes away, will not auto reconnect

### ISSUE THREAD

**Issue by kirkdwilson** [CircuitSetup/Split-Single-Phase-Energy-Meter#32]
I'm running version 2.5.4 firmware and if the access point is rebooted or temporarily goes away, the EMonESP will not auto reconnect when it comes back.  I have to power cycle the unit to get it to reconnect.  Can we put in a IfUp monitor to reconnect or cron job to reboot to get rid of this issue?

**Comment by CircuitSetup** [comment]
I would first recommend updating to the latest firmware, [which is here](https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/releases)

When your AP is rebooted, is the ESP32's LED still blinking? Normally it will go into AP mode if it cannot reconnect 3 times, waiting 10 seconds in-between each retry. It will stay in AP mode for 5 min, then reboot, and try to reconnect to your AP again, repeating the cycle. If you do not see the blue LED blinking, that means it probably froze at some point in the process. There were some bugs that were fixed that fix this issue in more recent versions. 

Also, if you still see frequent freezes from the ESP32, check to see that a browser hasn't been left open on the EmonESP setup page. Sometimes this can cause the ESP32 to run out of memory over time.
