### ISSUE TITLE
I am getting smoke from board on IC2

### ISSUE THREAD

**Issue by RichBoehle** [CircuitSetup/Split-Single-Phase-Energy-Meter#33]
I was using board yesterday, finally got it hooked up/configured and was going to "implement" today.  It just started smoking when I plugged in power supply.

I am using a power source output of "12AWC 1.25A"  Board did not smoke yesterday but just happened today.

**Comment by CircuitSetup** [comment]
This IC powers the board. It either was overpowered by the incoming voltage or something shorted. I'll arrange to send you a new board.
