### ISSUE TITLE
Won't Connect to MQTT Until Restart

### ISSUE THREAD

**Issue by rothnic** [CircuitSetup/Split-Single-Phase-Energy-Meter#35]
Not sure if this is more of a EmonESP issue or your particular setup. I just got mine working with emoncms, but was going to experiment with influxdb via mqtt. I put in my mqtt details and never could get it to connect. I think tried the publish mosquitto test server and still didn't connect.

I then restarted the device and it connected. It seems any time I change the settings I must restart for it to connect.

**Comment by CircuitSetup** [comment]
Glad you got it working! What version of EmonESP are you using?

**Comment by CircuitSetup** [comment]
This should have been fixed in v2.6. Please let me know if you are still having issues.
