### ISSUE TITLE
Can we measure current with one CT only?

### ISSUE THREAD

**Issue by aaamitsingh** [CircuitSetup/Split-Single-Phase-Energy-Meter#36]
In the description you have mentioned that two CT in opposite direction is required to measure the current.  Is this possible to do the same with the help of only one CT?

**Comment by CircuitSetup** [comment]
Do you mean 2 wires in 1 CT? If so, yes, this can be done as long as the CT is large enough and the 2 wires are fed through it in opposite directions. If they are the same direction power factor will be off and power will be calculated incorrectly.

**Comment by aaamitsingh** [comment]
Thanks for your response.  No I mean that I want to measure current with the one CT only. I don't want to use the second CT in opposite direction. 
Is there any way to read the pf and power correctly with one CT only?

**Comment by CircuitSetup** [comment]
Do you have split single phase power or single phase?

**Comment by aaamitsingh** [comment]
Single phase

**Comment by CircuitSetup** [comment]
You shouldn't have a problem only using 1 CT then. The meter will output power factor and power for that channel only. 

The 1 opposite CT only applies to split single phase power.

**Comment by aaamitsingh** [comment]
Great that means I can also monitor the current consumption of 2 different device with single board using 2 different CT?

http://www.hlktech.net/product_detail.php?ProId=64 
Can we use the above ultra small capsule transformer instead of mentioned bulky transformers?

**Comment by CircuitSetup** [comment]
You can as long as you are not reading the total power. There are outputs for single power channels in the Arduino library, and with ESPHome. EmonESP, by default, outputs the total wattage. 

No, that power module will not work. It has to be an AC to AC transformer with at least 1000mA, and between 9-12VAC output.

**Comment by aaamitsingh** [comment]
Thank you so much for clearing all my queries and fast response.  I'm closing this issue now but once we develop this product I will share the feedback with you.

Thank you one again.
