### ISSUE TITLE
Power is showing negative now?

### ISSUE THREAD

**Issue by scfigg** [CircuitSetup/Split-Single-Phase-Energy-Meter#44]
I've had this running just fine for a while now - and a couple weeks ago, it started showing power in the negatives. Not sure what's going on here. I've of course tried power cycling everything - any thoughts?

[](url)
![Capture](https://user-images.githubusercontent.com/4560481/103216724-53bf8f00-48dc-11eb-885a-7f8d8d39d921.PNG)

**Comment by rstanley75** [comment]
I just updated to 2.6 from 2.5.4 and suddenly I started having the same problem with negative power values.

![Screenshot 2021-01-10 203201](https://user-images.githubusercontent.com/4333539/104142898-1ac6f600-5383-11eb-8071-5ea2f41a3ebd.png)

**Comment by CircuitSetup** [comment]
1 of two things will show negative power: 

- You're exporting power to the grid (usually only happens with solar grids)
- A CT (or both) are backwards

@rstanley75 Previously in v2.5 there was a correction for any negatives. This was removed so that the power reading would calculate correctly.

**Comment by scfigg** [comment]
Can I ask you to clarify a CT being backwards? Do you mean plugged into the wrong 3.5mm port or configured incorrectly? I had it working correctly for me for the past year or so before any upgrades.

**Comment by CircuitSetup** [comment]
@scfigg literally the CT is backwards on the wire and has to be flipped around. If you were to plug the AC transformer into a plug on the opposite phase, this would also correct the negative issue.

**Comment by rstanley75** [comment]
> @scfigg literally the CT is backwards on the wire and has to be flipped around. If you were to plug the AC transformer into a plug on the opposite phase, this would also correct the negative issue.

Now that I'm thinking about it, when I was rewiring some circuits during a kitchen remodel I moved the breaker for the outlet my AC transformer is connected to.  At the time I hadn't given any thought to the AC transformer but I know it's on the other half of the split-phase from where it was originally.   I bet the old firmware was covering up my mistake.

**Comment by scfigg** [comment]
I guess I'm not fully understanding what is backwards. I rotated both of them around so that the it's 180 degrees rotated from where it was - and that didn't work. Still negative values. Why am I stupid? What am I doing/reading wrong here?

https://imgur.com/a/dPQh6eZ

**Comment by scfigg** [comment]
Nevermind - it was upside down. I guess that was the last thing to try! Looks like I'm getting data correctly now!
