### ISSUE TITLE
What is the latest version 2.6 or 2.6.1

### ISSUE THREAD

**Issue by JPElectron** [CircuitSetup/Split-Single-Phase-Energy-Meter#46]
I flashed mine thinking it would help with a different issue, but found the file on GitHub....

https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/blob/master/Software/EmonESP/src/src.ino.esp32.bin

...took me back to 2.6 instead of 2.6.1 which it shipped with?

**Comment by CircuitSetup** [comment]
My apologies for the confusion. 2.6.1 wasn't committed to github. What issues were you having with it previously?

**Comment by JPElectron** [comment]
WiFi connection issues - but I think what ended up solving it was removing the top cover and moving it further away from the metal breaker box.

**Comment by CircuitSetup** [comment]
If you're still having issues, please let me know. v3.0 is currently being worked on, and includes a number of improvements.
