### ISSUE TITLE
fried split circuit v1.4 rev 2

### ISSUE THREAD

**Issue by chaseadam** [CircuitSetup/Split-Single-Phase-Energy-Meter#47]
Installation running for a bit over 4 months paired with a Lolin knockoff esp8266 reporting to local emon. It was in "open air" installation (sitting on shelf next to power panel).

Smelled the classic electrical burning smell after breakfast and found the power meter off and a bit "toasty" (not the breakfast kind).
![IMG_20210206_095221](https://user-images.githubusercontent.com/333031/107122007-62964b80-6863-11eb-9e71-6890317433b6.jpg)
![IMG_20210206_095141](https://user-images.githubusercontent.com/333031/107122023-78a40c00-6863-11eb-9198-3106ada55420.jpg)

I am using one of the preferred high quality power supplies
![IMG_20210206_095234](https://user-images.githubusercontent.com/333031/107121994-4e524e80-6863-11eb-93ca-cc242e1eb876.jpg)

I haven't done much investigation yet, but will keep this thread up to date.

I suspect maybe the low quality dev board was pulling too much current and slowly damaged the regulator to the point of catastrophic failure.

Curious for others' hypotheses as well.

**Comment by CircuitSetup** [comment]
From the looks of it, the rectifier and power supply failed on the meter. I've only seen this happen once before, and the cause was likely because of a component failing. 

If you send me your order number I can send a replacement.

**Comment by chaseadam** [comment]
responded via https://circuitsetup.us/index.php/contact/
