### ISSUE TITLE
Calibration emonESP from Russia

### ISSUE THREAD

**Issue by skribbl84** [CircuitSetup/Split-Single-Phase-Energy-Meter#49]
Hi!
Two weeks ago I received a CircuitSetup Split Single-phase Energy Meter with two transformers 2x 16 mm round YHDC SCT-016 120 A CT Sensors.
I can’t calibrate Energy Meter for a long time.
Through a lot of trial and error, I got an approximate tension. In our electrical network, it is 230v.
In the emonESP Voltage field, I entered 4540. But I strongly doubt that this is the correct value.
I am using a 9v AC transformer.
In the field of calibration of transformers CT1 and CT2, I enter 39473.
But the power values ​​are not strong.
Please tell me how to correctly calculate the data for calibration.

**Comment by CircuitSetup** [comment]
The calibration procedure for voltage is here:  https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter#voltage-procedure

You will likely see a calibration value for voltage that is double the default, so start with 9080. Also make sure you have the field for frequency set to 50Hz, which is 389.
