### ISSUE TITLE
Negative values?

### ISSUE THREAD

**Issue by scfigg** [CircuitSetup/Split-Single-Phase-Energy-Meter#53]
Last year, I randomly started getting all of my values (such as wattage), being shown as negative. I was told I had the two connectors reversed on the wires - so I swapped the wires that they were connected to, and it started working again. As of like 2 months ago roughly, I started getting negative values again. I haven't changed any physical setup. Any idea if there's something on the software side that changed? or that I can change to start getting positive values again? 

![Capture](https://user-images.githubusercontent.com/4560481/125296555-080a8b00-e2ec-11eb-8e93-1385b5d22310.PNG)

**Comment by CircuitSetup** [comment]
Is it possible that the voltage reference was changed or plugged into a different outlet? Even if the voltage transformer was turned upside down, this would also reverse the phase, causing negative values for the current.
