### ISSUE TITLE
No Power with 3 different Jameco 9V Ac Adapters

### ISSUE THREAD

**Issue by luisgarcia87** [CircuitSetup/Split-Single-Phase-Energy-Meter#58]
Hi! I purchased a replacement Single Phase Energy Meter after my previous one stopped working after a blackout, but I was not able to turn it on using the Jameco 9V ac adapter (I have 3 of them). If I plug in a usb cable to the esp32 the pwr led on the single phase energy meter turns on red, but if I use the ac adapter neither the esp32 nor the energy meter turns on. Is it possible that all 3 of my adapters are not working? (2 of them were in use when the blackout happend but I don't know how the third one could be defective as well. If anyone can help I will greatly appreciate it. I already send an email to CircuitSetup as well.

Thank you

**Comment by CircuitSetup** [comment]
I'm pretty sure we resolved this via email. Closing.
