### ISSUE TITLE
Can I use a Jameco 112366 with board 1.4 rev3?

### ISSUE THREAD

**Issue by rb28z2** [CircuitSetup/Split-Single-Phase-Energy-Meter#59]
As the title says, I have a board version 1.4 rev 3, but according to the firmware and documentation, I can *only* use a Jameco 157041: https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/blob/master/Software/EmonESP/src/energy_meter.h#L63-L64

Is this actually the case or can I use a Jameco 112366 (essentially identical to the 15704 but is a 1.5A instead of a 1A) with a rev3 board?

**Comment by CircuitSetup** [comment]
Sorry I didn't see your question sooner. 

Yes, that transformer can be used. I would recommend calibrating it to the meter so you get accurate readings.
