### ISSUE TITLE
Using web interface and/or leaving it open causes ESP32 memory leak/crash

### ISSUE THREAD

**Issue by CircuitSetup** [CircuitSetup/Split-Single-Phase-Energy-Meter#6]
I think I might have found something, I noticed my energy meter crashing may be caused by having it's web page open in multiple tabs, it happened again yesterday when I didn't realize I already had a tab open in chrome, and opened another one, about 20 minutes later my meter dropped off the network.

I use an app for work called sysdweb to control systemd services, and when multiple users logged it it would crash similarly, probably no fix for it, but figured I'd offer the info.

I tried it again this morning, and 12 minutes later it crashed on me, and I needed to reboot it.

I ended up buying an internet switch so I can bounce it from anywhere.

_Originally posted by @jreiners in https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/issues/4#issuecomment-535126441_

**Comment by CircuitSetup** [comment]
Split this into a new issue. 

Recent updates to AsyncTCP: https://github.com/me-no-dev/AsyncTCP/pull/67
and ESPAsyncWebserver: https://github.com/me-no-dev/ESPAsyncWebServer/pull/591

Should solve this problem. Testing shortly...

**Comment by CircuitSetup** [comment]
According to the ESPAsyncWebServer fix, it may also cause a crash if you:

- reset the ESP32
- visit the web interface with a Chrome based browser

Doesn't matter if you close the browser or not, the session wasn't being closed properly in all cases, which would result in a memory leak and eventually cause a crash.

**Comment by jreiners** [comment]
Ahh nice catch, I always use Chrome.

**Comment by CircuitSetup** [comment]
Okay, this is fixed with v2.5.3 https://github.com/CircuitSetup/Split-Single-Phase-Energy-Meter/releases/tag/2.5.3

**Comment by jreiners** [comment]
Thanks, I'll check it out.

Justin Reiners
Reiners Cloud Consulting LLC
I'm happy to be your local Omaha distributor for 3CX and SimpleHelp!
Contact me for info.
