### ISSUE TITLE
Voltage measurement under load? 

### ISSUE THREAD

**Issue by Cat-Ion** [CircuitSetup/Split-Single-Phase-Energy-Meter#63]
I saw that the AC voltage input is also used to power the board. Is that wise? From what I've seen, ESP32s can use on the order of 1W while doing stuff with the wifi, which will affect the transformer's output quite a bit, since those aren't regulated. You can probably alleviate that somewhat by getting a transformer with a higher rated current, but it seems wiser to just... not load the measured voltage?

**Comment by CircuitSetup** [comment]
This was the trade off for having one thing plugged into the wall. The esp32 uses about 400mA when broadcasting an AP.  Luckily, this is usually only done when setting things up.

Regardless, charging the large capacitor puts a small dent in the voltage waveform. However, it doesn't effect it enough to change any readings in a significant way.
