### ISSUE TITLE
The fields sent from ESP don't match CircuitSetup defaults on SD card image

### ISSUE THREAD

**Issue by veggie2u** [CircuitSetup/Split-Single-Phase-Energy-Meter#9]
The fields I am getting from the ESP via MQTT are as follows:
0, V1, V2, CT1, CT2, totl, W, SolarV, SCT1, SCT2, totSolarl, SolarW, PF, temp, freq, freeram

These fields do not match the defaults from the SD image or the instructions image for creating a device and setting up inputs and feeds.

I am using the 'solar' version, which looks like 2 identical sensor modules. I just have one hooked up to Main.

**Comment by CircuitSetup** [comment]
This is being looked at by the EmonCMS people.

**Comment by CircuitSetup** [comment]
This should be fixed with this PR: https://github.com/emoncms/device/pull/48

**Comment by veggie2u** [comment]
There was an issue with the JSON that was fixed with https://github.com/emoncms/device/pull/49
